services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false

    evaisse\SimpleHttpBundle\Controller\ReplayController: ~
    evaisse\SimpleHttpBundle\Http\Kernel: ~
    evaisse\SimpleHttpBundle\Service\Helper: ~

    simple_http.helper: '@evaisse\SimpleHttpBundle\Service\Helper'
    simple_http.kernel: '@evaisse\SimpleHttpBundle\Http\Kernel'

    http:
        alias: simple_http.helper

    simple_http.logger:
        class: Symfony\Bridge\Monolog\Logger
        arguments: [simple_http]
        calls:
            - [pushHandler, ["@simple_http.logger.handler"]]

    simple_http.logger.handler:
        class: Monolog\Handler\StreamHandler
        arguments: ["%kernel.root_dir%/logs/%kernel.environment%.log", 0]


    simple_http.profiler.data_collector:
        class: evaisse\SimpleHttpBundle\DataCollector\ProfilerDataCollector
        public: true
        arguments:
            $debug: '%kernel.debug%'
        calls:
            - [ setStopWatch, [ "@debug.stopwatch" ] ]
        tags:
            - { name: kernel.event_subscriber }
            - { name: data_collector, template: "@SimpleHttp/Collector/profiler", id: "simplehttpprofiler" }

    evaisse\SimpleHttpBundle\Twig\Extension:
        arguments: ["@twig.loader"]
        tags:
            - { name: twig.extension }